package com.prosper.prospermentor.repository;

import com.prosper.prospermentor.entity.CyberSourceTransaction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository for CyberSource transaction data access
 */
@Repository
public interface CyberSourceTransactionRepository extends JpaRepository<CyberSourceTransaction, UUID> {

    /**
     * Find transaction by CyberSource transaction ID
     */
    Optional<CyberSourceTransaction> findByTransactionId(String transactionId);

    /**
     * Find transaction by payment ID
     */
    Optional<CyberSourceTransaction> findByPaymentId(UUID paymentId);

    /**
     * Find transaction by transaction UUID (generated by our system)
     */
    Optional<CyberSourceTransaction> findByTransactionUuid(String transactionUuid);

    /**
     * Find all transactions for a specific decision status
     */
    List<CyberSourceTransaction> findByDecision(String decision);

    /**
     * Find all transactions created within a date range
     */
    @Query("SELECT ct FROM CyberSourceTransaction ct WHERE ct.createdAt >= :startDate AND ct.createdAt <= :endDate ORDER BY ct.createdAt DESC")
    List<CyberSourceTransaction> findByDateRange(
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate
    );

    /**
     * Find all approved transactions
     */
    @Query("SELECT ct FROM CyberSourceTransaction ct WHERE UPPER(ct.decision) = 'ACCEPT' ORDER BY ct.createdAt DESC")
    List<CyberSourceTransaction> findAllApproved();

    /**
     * Find all declined transactions
     */
    @Query("SELECT ct FROM CyberSourceTransaction ct WHERE UPPER(ct.decision) = 'DECLINE' ORDER BY ct.createdAt DESC")
    List<CyberSourceTransaction> findAllDeclined();

    /**
     * Find transactions requiring review
     */
    @Query("SELECT ct FROM CyberSourceTransaction ct WHERE UPPER(ct.decision) = 'REVIEW' ORDER BY ct.createdAt DESC")
    List<CyberSourceTransaction> findAllRequiringReview();
}
