-- Migration: Add CyberSource payment gateway support
-- Purpose: Add fields to payments table and create cybersource_transactions table

-- Add CyberSource specific fields to existing payments table
ALTER TABLE payments
ADD COLUMN IF NOT EXISTS gateway_transaction_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS gateway_reference VARCHAR(255),
ADD COLUMN IF NOT EXISTS gateway_auth_code VARCHAR(100),
ADD COLUMN IF NOT EXISTS card_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS card_last_four VARCHAR(4);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_payments_gateway_transaction_id
ON payments(gateway_transaction_id);

CREATE INDEX IF NOT EXISTS idx_payments_payment_method
ON payments(payment_method);

-- Create detailed CyberSource transaction tracking table
CREATE TABLE IF NOT EXISTS cybersource_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id UUID NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  transaction_id VARCHAR(255) UNIQUE, -- Nullable: populated after CyberSource callback
  transaction_uuid VARCHAR(255) NOT NULL, -- Generated by us for tracking
  request_id VARCHAR(255),

  -- Authorization details
  auth_code VARCHAR(100),
  auth_amount DECIMAL(10,2),
  auth_response VARCHAR(10),
  auth_time TIMESTAMP,

  -- Card details (masked)
  card_type VARCHAR(50),
  card_number VARCHAR(20), -- masked format: ************1111
  card_expiry VARCHAR(10),

  -- Transaction details
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  decision VARCHAR(20) NOT NULL, -- ACCEPT, DECLINE, REVIEW, ERROR, CANCEL
  reason_code VARCHAR(10),
  message TEXT,

  -- Request data
  req_reference_number VARCHAR(255),
  req_bill_to_forename VARCHAR(100),
  req_bill_to_surname VARCHAR(100),
  req_bill_to_email VARCHAR(255),

  -- Signature verification
  signed_field_names TEXT,
  signature VARCHAR(512),

  -- Raw data for debugging
  raw_request TEXT,
  raw_response TEXT,

  -- Audit fields
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for CyberSource transactions
CREATE INDEX IF NOT EXISTS idx_cybersource_transactions_payment_id
ON cybersource_transactions(payment_id);

CREATE INDEX IF NOT EXISTS idx_cybersource_transactions_transaction_id
ON cybersource_transactions(transaction_id);

CREATE INDEX IF NOT EXISTS idx_cybersource_transactions_decision
ON cybersource_transactions(decision);

CREATE INDEX IF NOT EXISTS idx_cybersource_transactions_created_at
ON cybersource_transactions(created_at);

-- Add comments for documentation
COMMENT ON TABLE cybersource_transactions IS 'Detailed tracking of CyberSource card payment transactions';
COMMENT ON COLUMN payments.payment_method IS 'Payment method: MPESA, CARD, BANK_TRANSFER, PAYPAL, FREE';
COMMENT ON COLUMN payments.gateway_transaction_id IS 'Transaction ID from payment gateway (CyberSource, etc.)';
COMMENT ON COLUMN payments.gateway_reference IS 'Gateway reference number for the transaction';
COMMENT ON COLUMN payments.gateway_auth_code IS 'Authorization code from payment gateway';
COMMENT ON COLUMN payments.card_type IS 'Card type (Visa, Mastercard, Amex, etc.)';
COMMENT ON COLUMN payments.card_last_four IS 'Last 4 digits of card for display purposes';

COMMENT ON COLUMN cybersource_transactions.decision IS 'CyberSource decision: ACCEPT, DECLINE, REVIEW, ERROR, CANCEL';
COMMENT ON COLUMN cybersource_transactions.card_number IS 'Masked card number (e.g., ************1111)';
COMMENT ON COLUMN cybersource_transactions.raw_request IS 'Full request data for debugging';
COMMENT ON COLUMN cybersource_transactions.raw_response IS 'Full response data for debugging';
